export const FOOTNOTE_COVERAGE_BASE = {
  en: "Estimating service coverage from administrative data can provide more timely information on coverage trends, or highlight data quality concerns. Numerators are the volumes reported in HMIS, adjusted for data quality. Denominators are selected from UN projections, survey estimates, or derived from HMIS volume for related indicators. National projections are made by applying HMIS trends to the most recent survey data. Subnational estimates are more sensitive to poor data quality, and projections from surveys are not calculated.\n\nMICS data courtesy of UNICEF. Multiple Indicator Cluster Surveys (various rounds) New York City, New York.\n\nDHS data courtesy of ICF. Demographic and Health Surveys (various rounds). Rockville, Maryland.",
  fr: "L'estimation de la couverture des services à partir des données administratives peut fournir des informations plus rapides sur les tendances de couverture, ou mettre en évidence des problèmes de qualité des données. Les numérateurs sont les volumes déclarés dans le HMIS, ajustés pour la qualité des données. Les dénominateurs sont sélectionnés à partir des projections de l'ONU, des estimations d'enquête, ou dérivés du volume HMIS pour les indicateurs liés. Les projections nationales sont réalisées en appliquant les tendances HMIS aux données d'enquête les plus récentes. Les estimations sous-nationales sont plus sensibles à la mauvaise qualité des données, et les projections à partir des enquêtes ne sont pas calculées.\n\nDonnées MICS avec l'aimable autorisation de l'UNICEF. Enquêtes par grappes à indicateurs multiples (divers cycles). New York, New York.\n\nDonnées EDS avec l'aimable autorisation d'ICF. Enquêtes démographiques et de santé (divers cycles). Rockville, Maryland.",
  pt: "A estimativa da cobertura dos serviços a partir de dados administrativos pode fornecer informação mais atempada sobre as tendências de cobertura, ou evidenciar preocupações com a qualidade dos dados. Os numeradores são os volumes reportados no SIS, ajustados para a qualidade dos dados. Os denominadores são selecionados a partir das projeções da ONU, de estimativas de inquéritos, ou derivados do volume do SIS para indicadores relacionados. As projeções nacionais são feitas aplicando as tendências do SIS aos dados de inquérito mais recentes. As estimativas subnacionais são mais sensíveis à fraca qualidade dos dados, e as projeções a partir de inquéritos não são calculadas.\n\nDados MICS por cortesia da UNICEF. Inquéritos de Indicadores Múltiplos (várias rondas). Nova Iorque, Nova Iorque.\n\nDados DHS por cortesia da ICF. Inquéritos Demográficos e de Saúde (várias rondas). Rockville, Maryland.",
};

export const FOOTNOTE_COVERAGE_WITH_CURRENT_YEAR = {
  en: `${FOOTNOTE_COVERAGE_BASE.en}\n\nData for the current year reflect the period available at the time of analysis; population figures have been scaled to match the corresponding duration.`,
  fr: `${FOOTNOTE_COVERAGE_BASE.fr}\n\nLes données de l'année en cours reflètent la période disponible au moment de l'analyse ; les chiffres de population ont été ajustés pour correspondre à la durée correspondante.`,
  pt: `${FOOTNOTE_COVERAGE_BASE.pt}\n\nOs dados do ano em curso refletem o período disponível no momento da análise; os valores da população foram ajustados para corresponder à duração correspondente.`,
};

export const SUBCAPTION_DISCLAIMER = {
  en: "DATE_RANGE\nDISCLAIMER: These results use routine data to provide rigorous, but not official estimates. They should be interpreted considering any data quality or representation limitations, including data quality findings and any other country specific factors.",
  fr: "PLAGE_DE_DATES\nAVERTISSEMENT : Ces résultats utilisent des données de routine pour fournir des estimations rigoureuses mais non officielles. Ils doivent être interprétés en tenant compte des limitations de qualité des données ou de représentativité, y compris les résultats d'évaluation de la qualité des données et tout autre facteur spécifique au pays.",
  pt: "INTERVALO_DE_DATAS\nAVISO: Estes resultados utilizam dados de rotina para fornecer estimativas rigorosas, mas não oficiais. Devem ser interpretados tendo em conta quaisquer limitações de qualidade dos dados ou de representatividade, incluindo as conclusões sobre a qualidade dos dados e quaisquer outros fatores específicos do país.",
};
