import type { MetricDefinitionGithub, VizPreset } from "../../.validation/_module_definition_github.ts";

export const vizPresets: VizPreset[] = [];

export const metric: MetricDefinitionGithub = {
  id: "m4a-02-03",
  resultsObjectId: "M5_combined_results_admin3.csv",
  valueProps: ["value"],
  valueFunc: "AVG",
  valueLabelReplacements: {
    best: "Best",
    survey: "Survey",
    danc1_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on ANC 1st visits.",
    danc1_delivery: "Estimated number of deliveries derived from HMIS data on ANC 1st visits.",
    danc1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on ANC 1st visits.",
    danc1_livebirth: "Estimated number of live births derived from HMIS data on ANC 1st visits.",
    danc1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on ANC 1st visits.",
    danc1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on ANC 1st visits.",
    danc1_pregnancy: "Estimated number of pregnancies derived from HMIS data on ANC 1st visits.",
    dbcg_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on BCG doses.",
    dbcg_livebirth: "Estimated number of live births derived from HMIS data on BCG doses.",
    dbcg_pregnancy: "Estimated number of pregnancies derived from HMIS data on BCG doses.",
    ddelivery_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on institutional deliveries.",
    ddelivery_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on institutional deliveries.",
    ddelivery_livebirth: "Estimated number of live births derived from HMIS data on institutional deliveries.",
    ddelivery_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on institutional deliveries.",
    ddelivery_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on institutional deliveries.",
    ddelivery_pregnancy: "Estimated number of pregnancies derived from HMIS data on institutional deliveries.",
    dlivebirths_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on live births.",
    dlivebirths_delivery: "Estimated number of deliveries derived from HMIS data on live births.",
    dlivebirths_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on live births.",
    dlivebirths_livebirth: "Estimated number of live births derived from HMIS data on live births.",
    dlivebirths_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on live births.",
    dlivebirths_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on live births.",
    dlivebirths_pregnancy: "Estimated number of pregnancies derived from HMIS data on live births.",
    dpenta1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on Penta-1 doses.",
    dpenta1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on Penta-1 doses.",
    dpenta1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on Penta-1 doses.",
    dwpp_dpt: "Estimated number of infants eligible for DPT1 based on UN WPP estimates.",
    dwpp_livebirth: "Estimated number of live births based on UN WPP estimates.",
    dwpp_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) based on UN WPP estimates.",
    dwpp_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) based on UN WPP estimates.",
    dwpp_pregnancy: "Estimated number of pregnancies based on UN WPP estimates.",
    source_anc1: "HMIS data on ANC 1st visits",
    source_delivery: "HMIS data on institutional deliveries",
    source_bcg: "HMIS data on BCG doses",
    source_penta1: "HMIS data on Penta-1 doses",
    source_wpp: "UN WPP estimates",
    source_livebirths: "HMIS data on live births",
    target_pregnancy: "Pregnancies",
    target_delivery: "Deliveries",
    target_birth: "Total births (live + stillbirths)",
    target_livebirth: "Live births",
    target_dpt: "Infants eligible for DPT1",
    target_measles1: "Children eligible for measles dose 1 (MCV1)",
    target_measles2: "Children eligible for measles dose 2 (MCV2)",
    target_vitaminA: "Children aged 6-59 months eligible for Vitamin A supplementation",
    target_fully_immunized: "Children under 1 year eligible for full immunization",
  },
  label: {
    en: "Coverage estimated with different denominators",
    fr: "Couverture estimée avec différents dénominateurs",
  },
  variantLabel: {
    en: "Admin area 3",
    fr: "Zone administrative 3",
  },
  requiredDisaggregationOptions: [
    "denominator_best_or_survey",
    "admin_area_3",
    "indicator_common_id",
    "year",
  ],
  formatAs: "percent",
  aiDescription: {
    summary: {
      en: "District-level coverage estimates using alternative denominators at admin area 3 level.",
      fr: "Estimations de couverture au niveau du district utilisant des dénominateurs alternatifs au niveau de la zone administrative 3.",
    },
    methodology: {
      en: "AVG of coverage with different denominator types at district level. Highest geographic resolution for coverage estimation.",
      fr: "Moyenne de la couverture avec différents types de dénominateur au niveau du district. Plus haute résolution géographique pour l'estimation de couverture.",
    },
    interpretation: {
      en: "District-level denominator uncertainty typically highest. Use to understand micro-level coverage patterns but interpret with caution.",
      fr: "L'incertitude du dénominateur au niveau du district est généralement la plus élevée. Utiliser pour comprendre les modèles de couverture micro-niveau avec prudence.",
    },
    typicalRange: {
      en: "0-100%. Wide variation across denominators common due to small sample sizes and denominator uncertainty.",
      fr: "0-100%. Variation large entre dénominateurs commune en raison de petites tailles d'échantillon et incertitude du dénominateur.",
    },
    disaggregationGuidance: {
      en: "Always disaggregate by denominator_best_or_survey, admin_area_3, indicator_common_id, and year (all required). High uncertainty at this level - consider aggregating to admin area 2.",
      fr: "Toujours désagréger par denominator_best_or_survey, admin_area_3, indicator_common_id et year (tous requis). Incertitude élevée à ce niveau - considérer l'agrégation à la zone administrative 2.",
    },
    caveats: null,
  },
  postAggregationExpression: null,
  importantNotes: null,
  hide: false,
  vizPresets,
};
