import type { MetricDefinitionGithub, VizPreset } from "../../.validation/_module_definition_github.ts";

export const vizPresets: VizPreset[] = [];

export const metric: MetricDefinitionGithub = {
  id: "m4a-01-03",
  resultsObjectId: "M5_denominators_admin3.csv",
  valueProps: ["value"],
  valueFunc: "AVG",
  valueLabelReplacements: {
    best: "Best",
    survey: "Survey",
    danc1_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on ANC 1st visits.",
    danc1_delivery: "Estimated number of deliveries derived from HMIS data on ANC 1st visits.",
    danc1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on ANC 1st visits.",
    danc1_livebirth: "Estimated number of live births derived from HMIS data on ANC 1st visits.",
    danc1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on ANC 1st visits.",
    danc1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on ANC 1st visits.",
    danc1_pregnancy: "Estimated number of pregnancies derived from HMIS data on ANC 1st visits.",
    dbcg_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on BCG doses.",
    dbcg_livebirth: "Estimated number of live births derived from HMIS data on BCG doses.",
    dbcg_pregnancy: "Estimated number of pregnancies derived from HMIS data on BCG doses.",
    ddelivery_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on institutional deliveries.",
    ddelivery_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on institutional deliveries.",
    ddelivery_livebirth: "Estimated number of live births derived from HMIS data on institutional deliveries.",
    ddelivery_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on institutional deliveries.",
    ddelivery_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on institutional deliveries.",
    ddelivery_pregnancy: "Estimated number of pregnancies derived from HMIS data on institutional deliveries.",
    dlivebirths_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on live births.",
    dlivebirths_delivery: "Estimated number of deliveries derived from HMIS data on live births.",
    dlivebirths_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on live births.",
    dlivebirths_livebirth: "Estimated number of live births derived from HMIS data on live births.",
    dlivebirths_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on live births.",
    dlivebirths_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on live births.",
    dlivebirths_pregnancy: "Estimated number of pregnancies derived from HMIS data on live births.",
    dpenta1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on Penta-1 doses.",
    dpenta1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on Penta-1 doses.",
    dpenta1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on Penta-1 doses.",
    dwpp_dpt: "Estimated number of infants eligible for DPT1 based on UN WPP estimates.",
    dwpp_livebirth: "Estimated number of live births based on UN WPP estimates.",
    dwpp_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) based on UN WPP estimates.",
    dwpp_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) based on UN WPP estimates.",
    dwpp_pregnancy: "Estimated number of pregnancies based on UN WPP estimates.",
    source_anc1: "HMIS data on ANC 1st visits",
    source_delivery: "HMIS data on institutional deliveries",
    source_bcg: "HMIS data on BCG doses",
    source_penta1: "HMIS data on Penta-1 doses",
    source_wpp: "UN WPP estimates",
    source_livebirths: "HMIS data on live births",
    target_pregnancy: "Pregnancies",
    target_delivery: "Deliveries",
    target_birth: "Total births (live + stillbirths)",
    target_livebirth: "Live births",
    target_dpt: "Infants eligible for DPT1",
    target_measles1: "Children eligible for measles dose 1 (MCV1)",
    target_measles2: "Children eligible for measles dose 2 (MCV2)",
    target_vitaminA: "Children aged 6-59 months eligible for Vitamin A supplementation",
    target_fully_immunized: "Children under 1 year eligible for full immunization",
  },
  label: {
    en: "Denominator values",
    fr: "Valeurs de dénominateur",
  },
  variantLabel: {
    en: "Admin area 3",
    fr: "Zone administrative 3",
  },
  requiredDisaggregationOptions: ["denominator", "admin_area_3", "year"],
  formatAs: "number",
  aiDescription: {
    summary: {
      en: "District-level population denominators for coverage calculation at admin area 3 level.",
      fr: "Dénominateurs de population au niveau du district pour le calcul de couverture au niveau de la zone administrative 3.",
    },
    methodology: {
      en: "AVG of district-level denominators. Finest geographic resolution available. Only generated when ANALYSIS_LEVEL includes admin_area_3.",
      fr: "Moyenne des dénominateurs au niveau du district. Résolution géographique la plus fine disponible. Généré uniquement lorsque ANALYSIS_LEVEL inclut admin_area_3.",
    },
    interpretation: {
      en: "District denominators most uncertain due to small sample sizes and population mobility. Use with caution for micro-level targeting.",
      fr: "Les dénominateurs de district sont les plus incertains en raison de petites tailles d'échantillon et mobilité de la population.",
    },
    typicalRange: {
      en: "Varies by district size. Smaller than admin area 2 denominators, proportional to population.",
      fr: "Varie selon la taille du district. Plus petit que les dénominateurs de zone administrative 2, proportionnel à la population.",
    },
    disaggregationGuidance: {
      en: "Always disaggregate by denominator, admin_area_3, and year (all required). Interpret with caution due to denominator uncertainty at this level.",
      fr: "Toujours désagréger par denominator, admin_area_3 et year (tous requis). Interpréter avec prudence en raison de l'incertitude du dénominateur à ce niveau.",
    },
    caveats: null,
  },
  postAggregationExpression: null,
  importantNotes: null,
  hide: false,
  vizPresets,
};
