import type { MetricDefinitionGithub, VizPreset } from "../../.validation/_module_definition_github.ts";

export const vizPresets: VizPreset[] = [];

export const metric: MetricDefinitionGithub = {
  id: "m4a-01-02",
  resultsObjectId: "M5_denominators_admin2.csv",
  valueProps: ["value"],
  valueFunc: "AVG",
  valueLabelReplacements: {
    best: "Best",
    survey: "Survey",
    danc1_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on ANC 1st visits.",
    danc1_delivery: "Estimated number of deliveries derived from HMIS data on ANC 1st visits.",
    danc1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on ANC 1st visits.",
    danc1_livebirth: "Estimated number of live births derived from HMIS data on ANC 1st visits.",
    danc1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on ANC 1st visits.",
    danc1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on ANC 1st visits.",
    danc1_pregnancy: "Estimated number of pregnancies derived from HMIS data on ANC 1st visits.",
    dbcg_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on BCG doses.",
    dbcg_livebirth: "Estimated number of live births derived from HMIS data on BCG doses.",
    dbcg_pregnancy: "Estimated number of pregnancies derived from HMIS data on BCG doses.",
    ddelivery_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on institutional deliveries.",
    ddelivery_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on institutional deliveries.",
    ddelivery_livebirth: "Estimated number of live births derived from HMIS data on institutional deliveries.",
    ddelivery_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on institutional deliveries.",
    ddelivery_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on institutional deliveries.",
    ddelivery_pregnancy: "Estimated number of pregnancies derived from HMIS data on institutional deliveries.",
    dlivebirths_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on live births.",
    dlivebirths_delivery: "Estimated number of deliveries derived from HMIS data on live births.",
    dlivebirths_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on live births.",
    dlivebirths_livebirth: "Estimated number of live births derived from HMIS data on live births.",
    dlivebirths_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on live births.",
    dlivebirths_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on live births.",
    dlivebirths_pregnancy: "Estimated number of pregnancies derived from HMIS data on live births.",
    dpenta1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on Penta-1 doses.",
    dpenta1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on Penta-1 doses.",
    dpenta1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on Penta-1 doses.",
    dwpp_dpt: "Estimated number of infants eligible for DPT1 based on UN WPP estimates.",
    dwpp_livebirth: "Estimated number of live births based on UN WPP estimates.",
    dwpp_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) based on UN WPP estimates.",
    dwpp_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) based on UN WPP estimates.",
    dwpp_pregnancy: "Estimated number of pregnancies based on UN WPP estimates.",
    source_anc1: "HMIS data on ANC 1st visits",
    source_delivery: "HMIS data on institutional deliveries",
    source_bcg: "HMIS data on BCG doses",
    source_penta1: "HMIS data on Penta-1 doses",
    source_wpp: "UN WPP estimates",
    source_livebirths: "HMIS data on live births",
    target_pregnancy: "Pregnancies",
    target_delivery: "Deliveries",
    target_birth: "Total births (live + stillbirths)",
    target_livebirth: "Live births",
    target_dpt: "Infants eligible for DPT1",
    target_measles1: "Children eligible for measles dose 1 (MCV1)",
    target_measles2: "Children eligible for measles dose 2 (MCV2)",
    target_vitaminA: "Children aged 6-59 months eligible for Vitamin A supplementation",
    target_fully_immunized: "Children under 1 year eligible for full immunization",
  },
  label: {
    en: "Denominator values",
    fr: "Valeurs de dénominateur",
  },
  variantLabel: {
    en: "Admin area 2",
    fr: "Zone administrative 2",
  },
  requiredDisaggregationOptions: ["denominator", "admin_area_2", "year"],
  formatAs: "number",
  aiDescription: {
    summary: {
      en: "Subnational population denominators for coverage calculation at admin area 2 level.",
      fr: "Dénominateurs de population sous-nationaux pour le calcul de couverture au niveau de la zone administrative 2.",
    },
    methodology: {
      en: "AVG of denominators derived from subnational HMIS data and survey estimates. UNWPP denominators not available at this level. Uses national-level methodology adapted to subnational populations.",
      fr: "Moyenne des dénominateurs dérivés des données HMIS sous-nationales et estimations d'enquête. Dénominateurs UNWPP non disponibles à ce niveau.",
    },
    interpretation: {
      en: "Subnational denominators enable regional coverage monitoring. Compare across admin areas to assess population estimate consistency. Larger regional variation suggests denominator uncertainty.",
      fr: "Les dénominateurs sous-nationaux permettent la surveillance de la couverture régionale. Comparer entre zones administratives pour évaluer la cohérence des estimations.",
    },
    typicalRange: {
      en: "Varies by region size and population. Proportional to national denominators.",
      fr: "Varie selon la taille de la région et la population. Proportionnel aux dénominateurs nationaux.",
    },
    disaggregationGuidance: {
      en: "Always disaggregate by denominator, admin_area_2, and year (all required). Compare denominator sources to assess regional data quality.",
      fr: "Toujours désagréger par denominator, admin_area_2 et year (tous requis). Comparer les sources de dénominateur pour évaluer la qualité des données régionales.",
    },
    caveats: null,
  },
  postAggregationExpression: null,
  importantNotes: null,
  hide: false,
  vizPresets,
};
