import type { MetricDefinitionGithub, VizPreset } from "../../.validation/_module_definition_github.ts";

export const vizPresets: VizPreset[] = [];

export const metric: MetricDefinitionGithub = {
  id: "m4a-02-02",
  resultsObjectId: "M5_combined_results_admin2.csv",
  valueProps: ["value"],
  valueFunc: "AVG",
  valueLabelReplacements: {
    best: "Best",
    survey: "Survey",
    danc1_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on ANC 1st visits.",
    danc1_delivery: "Estimated number of deliveries derived from HMIS data on ANC 1st visits.",
    danc1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on ANC 1st visits.",
    danc1_livebirth: "Estimated number of live births derived from HMIS data on ANC 1st visits.",
    danc1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on ANC 1st visits.",
    danc1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on ANC 1st visits.",
    danc1_pregnancy: "Estimated number of pregnancies derived from HMIS data on ANC 1st visits.",
    dbcg_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on BCG doses.",
    dbcg_livebirth: "Estimated number of live births derived from HMIS data on BCG doses.",
    dbcg_pregnancy: "Estimated number of pregnancies derived from HMIS data on BCG doses.",
    ddelivery_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on institutional deliveries.",
    ddelivery_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on institutional deliveries.",
    ddelivery_livebirth: "Estimated number of live births derived from HMIS data on institutional deliveries.",
    ddelivery_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on institutional deliveries.",
    ddelivery_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on institutional deliveries.",
    ddelivery_pregnancy: "Estimated number of pregnancies derived from HMIS data on institutional deliveries.",
    dlivebirths_birth: "Estimated number of total births (live + stillbirths) derived from HMIS data on live births.",
    dlivebirths_delivery: "Estimated number of deliveries derived from HMIS data on live births.",
    dlivebirths_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on live births.",
    dlivebirths_livebirth: "Estimated number of live births derived from HMIS data on live births.",
    dlivebirths_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on live births.",
    dlivebirths_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on live births.",
    dlivebirths_pregnancy: "Estimated number of pregnancies derived from HMIS data on live births.",
    dpenta1_dpt: "Estimated number of infants eligible for DPT1 derived from HMIS data on Penta-1 doses.",
    dpenta1_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) derived from HMIS data on Penta-1 doses.",
    dpenta1_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) derived from HMIS data on Penta-1 doses.",
    dwpp_dpt: "Estimated number of infants eligible for DPT1 based on UN WPP estimates.",
    dwpp_livebirth: "Estimated number of live births based on UN WPP estimates.",
    dwpp_measles1: "Estimated number of children eligible for measles dose 1 (MCV1) based on UN WPP estimates.",
    dwpp_measles2: "Estimated number of children eligible for measles dose 2 (MCV2) based on UN WPP estimates.",
    dwpp_pregnancy: "Estimated number of pregnancies based on UN WPP estimates.",
    source_anc1: "HMIS data on ANC 1st visits",
    source_delivery: "HMIS data on institutional deliveries",
    source_bcg: "HMIS data on BCG doses",
    source_penta1: "HMIS data on Penta-1 doses",
    source_wpp: "UN WPP estimates",
    source_livebirths: "HMIS data on live births",
    target_pregnancy: "Pregnancies",
    target_delivery: "Deliveries",
    target_birth: "Total births (live + stillbirths)",
    target_livebirth: "Live births",
    target_dpt: "Infants eligible for DPT1",
    target_measles1: "Children eligible for measles dose 1 (MCV1)",
    target_measles2: "Children eligible for measles dose 2 (MCV2)",
    target_vitaminA: "Children aged 6-59 months eligible for Vitamin A supplementation",
    target_fully_immunized: "Children under 1 year eligible for full immunization",
  },
  label: {
    en: "Coverage estimated with different denominators",
    fr: "Couverture estimée avec différents dénominateurs",
  },
  variantLabel: {
    en: "Admin area 2",
    fr: "Zone administrative 2",
  },
  requiredDisaggregationOptions: [
    "denominator_best_or_survey",
    "admin_area_2",
    "indicator_common_id",
    "year",
  ],
  formatAs: "percent",
  aiDescription: {
    summary: {
      en: "Subnational coverage estimates using alternative denominators at admin area 2 level.",
      fr: "Estimations de couverture sous-nationales utilisant des dénominateurs alternatifs au niveau de la zone administrative 2.",
    },
    methodology: {
      en: "AVG of coverage with different denominator types at subnational level. National-only denominators (e.g., UNWPP) replaced with subnational alternatives.",
      fr: "Moyenne de la couverture avec différents types de dénominateur au niveau sous-national. Dénominateurs nationaux uniquement remplacés par alternatives sous-nationales.",
    },
    interpretation: {
      en: "Enables assessment of denominator uncertainty at regional level. Useful for understanding geographic variation in coverage and denominator quality.",
      fr: "Permet l'évaluation de l'incertitude du dénominateur au niveau régional. Utile pour comprendre la variation géographique de la couverture.",
    },
    typicalRange: {
      en: "0-100%. Variation across denominators indicates uncertainty in regional coverage estimates.",
      fr: "0-100%. La variation entre dénominateurs indique une incertitude dans les estimations de couverture régionale.",
    },
    disaggregationGuidance: {
      en: "Always disaggregate by denominator_best_or_survey, admin_area_2, indicator_common_id, and year (all required). Compare denominator types to assess regional estimate uncertainty.",
      fr: "Toujours désagréger par denominator_best_or_survey, admin_area_2, indicator_common_id et year (tous requis). Comparer les types de dénominateur pour évaluer l'incertitude des estimations régionales.",
    },
    caveats: null,
  },
  postAggregationExpression: null,
  importantNotes: null,
  hide: false,
  vizPresets,
};
